### ISSUE TITLE
已测

### ISSUE THREAD

**Issue by luciouskami** [w4454962/jass-parser#1]
确实有点慢

**Comment by w4454962** [comment]
太慢了 打算弃了，用手写解析器重写一个， 这个pegtl的设计有很大的问题，主要问题就是有太多垃圾节点的构造跟析构导致速度缓慢

**Comment by w4454962** [comment]
pegtl的词法分析占10%的时间 ，解析树节点产生占80%，其中包含大量垃圾节点的构造跟析构， 语义分析仅占10%，
